# MCP File Server Configuration

# 服务器配置
server:
  outputFormat: "yaml"  # yaml | json
  debug: false
  cors: true

# Redis集群配置
redis:
  addr: 192.168.0.125:6379
  password: kcserver
  db: 0

# 认证配置
auth:
  addr: "https://test.vextra.cn/api/v1/access/token"
  expire: 3600

storage:
  provider: minio
  endpoint: "192.168.0.125:9000"
  region: "zhuhai-1"
  accessKeyID: "59L3pDWuk9oLQWIgytCI"
  secretAccessKey: "GmwAzetY1L0jU4pUAqpO7RJGIsG7k3gozVH6whoJ"
  stsAccessKeyID: "user"
  stsSecretAccessKey: "GmwAzetY1L0jU4pUAqpO7RJGIsG7k3gozVH6whoJ"
  mcpBucket: "mcp"

storage_public_url:
  mcp: https://storage.test.vextra.cn/mcp


ws_url: "ws://localhost:8081/api/v1/access/ws"